### ISSUE TITLE
java.lang.IllegalStateException : Exception findById block

### ISSUE THREAD

**Issue by moueza** [moueza/accessing-data-jpa-springboot-guide#2]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.1.RELEASE)

2020-07-18 13:24:04.226  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Starting AccessingDataJpaApplication on oscillan1 with PID 11602 (/home/peter/git/accessing-data-jpa-springboot-guide/accessing-data-jpa/target/classes started by peter in /home/peter/git/accessing-data-jpa-springboot-guide/accessing-data-jpa)
2020-07-18 13:24:04.236  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : No active profile set, falling back to default profiles: default
2020-07-18 13:24:05.924  INFO 11602 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFERRED mode.
2020-07-18 13:24:06.173  INFO 11602 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 210ms. Found 1 JPA repository interfaces.
2020-07-18 13:24:08.200  INFO 11602 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-07-18 13:24:08.449  INFO 11602 --- [         task-1] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2020-07-18 13:24:08.758  INFO 11602 --- [         task-1] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.17.Final
2020-07-18 13:24:08.952  INFO 11602 --- [           main] DeferredRepositoryInitializationListener : Triggering deferred initialization of Spring Data repositories…
2020-07-18 13:24:09.473  INFO 11602 --- [         task-1] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-07-18 13:24:09.970  INFO 11602 --- [         task-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2020-07-18 13:24:12.480  INFO 11602 --- [         task-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2020-07-18 13:24:12.902  INFO 11602 --- [         task-1] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL57Dialect
2020-07-18 13:24:16.043  INFO 11602 --- [         task-1] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2020-07-18 13:24:16.067  INFO 11602 --- [         task-1] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2020-07-18 13:24:17.491  INFO 11602 --- [           main] DeferredRepositoryInitializationListener : Spring Data repositories initialized!
2020-07-18 13:24:17.540  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Started AccessingDataJpaApplication in 14.643 seconds (JVM running for 16.054)
2020-07-18 13:24:18.637  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customers found with findAll():
2020-07-18 13:24:18.638  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : -------------------------------
2020-07-18 13:24:19.377  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=2, firstName='Jack', lastName='Bauer']
2020-07-18 13:24:19.382  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=3, firstName='Chloe', lastName='O'Brian']
2020-07-18 13:24:19.382  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=4, firstName='Kim', lastName='Bauer']
2020-07-18 13:24:19.383  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=5, firstName='David', lastName='Palmer']
2020-07-18 13:24:19.386  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=6, firstName='Michelle', lastName='Dessler']
2020-07-18 13:24:19.386  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=7, firstName='Jack', lastName='Bauer']
2020-07-18 13:24:19.387  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=8, firstName='Chloe', lastName='O'Brian']
2020-07-18 13:24:19.387  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=9, firstName='Kim', lastName='Bauer']
2020-07-18 13:24:19.387  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=10, firstName='David', lastName='Palmer']
2020-07-18 13:24:19.388  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=11, firstName='Michelle', lastName='Dessler']
2020-07-18 13:24:19.388  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=12, firstName='Jack', lastName='Bauer']
2020-07-18 13:24:19.388  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=13, firstName='Chloe', lastName='O'Brian']
2020-07-18 13:24:19.388  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=14, firstName='Kim', lastName='Bauer']
2020-07-18 13:24:19.389  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=15, firstName='David', lastName='Palmer']
2020-07-18 13:24:19.391  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=16, firstName='Michelle', lastName='Dessler']
2020-07-18 13:24:19.393  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=17, firstName='Jack', lastName='Bauer']
2020-07-18 13:24:19.396  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=18, firstName='Chloe', lastName='O'Brian']
2020-07-18 13:24:19.400  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=19, firstName='Kim', lastName='Bauer']
2020-07-18 13:24:19.403  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=20, firstName='David', lastName='Palmer']
2020-07-18 13:24:19.405  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer[id=21, firstName='Michelle', lastName='Dessler']
2020-07-18 13:24:19.406  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : 
2020-07-18 13:24:19.479  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : Customer found with findById(1L):
2020-07-18 13:24:19.481  INFO 11602 --- [           main] c.e.a.AccessingDataJpaApplication        : --------------------------------
2020-07-18 13:24:19.510  INFO 11602 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-18 13:24:19.530 ERROR 11602 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at com.example.accessingdatajpa.AccessingDataJpaApplication.main(AccessingDataJpaApplication.java:16) [classes/:na]
Caused by: java.lang.NullPointerException: null
	at com.example.accessingdatajpa.AccessingDataJpaApplication.lambda$0(AccessingDataJpaApplication.java:41) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 5 common frames omitted

2020-07-18 13:24:19.539  INFO 11602 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2020-07-18 13:24:19.548  INFO 11602 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-07-18 13:24:19.554  INFO 11602 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-07-18 13:24:19.654  INFO 11602 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

**Comment by moueza** [comment]
Perhaps due to MySQL instead of H2
